spring:
  h2:
    console:
     enabled: true
     path: /h2-console
  datasource:
    url: jdbc:h2:mem:ykdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080